### ISSUE TITLE
Blank pages with one link and MySQL Connection error

### ISSUE THREAD

**Issue by darkmatus** [coolcsn/CsnUser#1]
I installed CsnUser to test it for an small site.
After following the install instruction I call on my developing machine "127.0.0.1/user"
and all what I got was an white page with an link to /user.
The same occurred when I call "127.0.0.1/forgotten-password".

The other problem is that I got a "SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)".
The correct databese settings are in the doctrineorm.local.php and works fine on the terminal.

**Comment by coolcsn** [comment]
It is obvious there is no connection to the MySQL server. "SQLSTATE[HY000] [2002] Connection refused". Just for any case I will try to install the module on a development machine to make sure everything works fine and I will get back to you.

**Comment by darkmatus** [comment]
Okay the error was that the pre-defined 'localhost' won't work.
I need to change it to 127.0.0.1 ._.
