### ISSUE TITLE
CreateUserForm issue

### ISSUE THREAD

**Issue by ilueckel** [coolcsn/CsnUser#16]
Hi,
I recently updated my CsnUser module and are facing some problems at the moment:

```
$builder = new DoctrineAnnotationBuilder($entityManager);
$this->form = $builder->createForm($userEntity);

$this->addCommonFields();
```

Does not seem to create the required/common form elements like 'username', 'password' etc which led to php errors. I bypassed this by adding more common fields but I most likely missed something else here. Can you give a short answer if I'm doing something wrong here.

**Comment by coolcsn** [comment]
Please, use version 0.1.0 of CsnUser module. Do not upgrade yet to 0.2.0 or do not dev-master! The development branch is not very well tested, stable and compatible with the other modules, yet. We will work on fixing this problem within the next month. The common fields should show up without adding them manually, but if it works the way you did it, then it is OK.

**Comment by ilueckel** [comment]
It seems that the ZendDeveloperTools interfere with the DoctrineAnnotationBuilder. So the fault is not your side.
