### ISSUE TITLE
Account confirmation issue

### ISSUE THREAD

**Issue by mikaint** [coolcsn/CsnUser#3]
Hi,

I was getting an error message when opening the link for new registration confirmation. I  used $e->getMessage() to see what's wrong and the output was 'Your proxy directory must be writable'. Could you please tell me which directory is this?

Thanks,

C.

**Comment by coolcsn** [comment]
Create directory data/DoctrineORMModule/Proxy and make sure your application has write access to it. This is part of the DoctrineORMModule installation instructions. You can join the developers of these modules in IRC channel "#coolcsn" at http://freenode.net/. Maybe you will get faster answers to your questions.

**Comment by mikaint** [comment]
Cool, thank you!
