### ISSUE TITLE
 An error occurred during execution - Zend\I18n\Exception\ExtensionNotLoadedException

### ISSUE THREAD

**Issue by omrai** [coolcsn/CsnUser#33]
i install csn-module and  config as given in documentation , when i try  signup page execution it show error 
An error occurred during execution - Zend\I18n\Exception\ExtensionNotLoadedException in 
in ...\vendor\zendframework\zendframework\library\Zend\I18n\Filter\AbstractLocale.php:24
and exception message show - Zend\I18n\Filter component requires the intl PHP extension.
i am new in zend and no idea about this....plz solve this

**Comment by Alexandre-T** [comment]
Hello,

Answer is in the question : Install the intl PHP extension.

http://php.net/manual/fr/intl.setup.php

**Comment by omrai** [comment]
i am already use php 5.4+

**Comment by coolcsn** [comment]
You still have to install and enable the "intl" extension. Make sure when you execute phpinfo(); in the list there is an "intl" section. You are missing the intl extension. It is used by one of the ZF2 validators.

**Comment by Alexandre-T** [comment]
The php version doesn't matter in your problem, Intl is an extension and isn't install by default. You have to install it as describe in my link.

**Comment by omrai** [comment]
thanks you so much it resolve issues
