### ISSUE TITLE
Operation timed out

### ISSUE THREAD

**Issue by adarshkhatri** [coolcsn/CsnUser#34]
I am not able to signup using this extension.

It says:
Zend\Mail\Protocol\Exception\RuntimeException
File: /Applications/XAMPP/xamppfiles/htdocs/skeleton/vendor/zendframework/zend-mail/src/Protocol/Smtp.php:179
Message: Unable to connect via TLS

My guess is SMTP settings not working correctly.

return array(
    'mail' => array(
        'transport' => array(
            'options' => array(
                'host' => 'smtp.mail.yahoo.com',
                //'host' => 'smtp.gmail.com',
                'connection_class'  => 'plain',
                //'port' => '465',
                'connection_config' => array(
                    'username' => 'acount@yahoo.com',
                    'password' => 'password',
                    'ssl' => 'tls'
                ),
            ),  
        ),
    ),
);

Please suggest.

**Comment by wingman007** [comment]
Yes! Your guess is right. The PHP can not establish connection to your SMTP server. You can try to comment 'ssl' => 'tls'. Look the message "Message: Unable to connect via TLS". Try to use a SMTP server for which you know all settings. Try to use it first with "Mozilla Thunderbird" for example. And after that use the exact same settings to configure your Zend app.

**Comment by adarshkhatri** [comment]
I have also tried with setting port to 465, but it says "Could not read smtp.mail.yahoo.com", and also tried with my godaddy SMTP settings, same result.

Not sure if my XAMPP or any other is not configured correctly.
I am bit of lost here.

**Comment by wingman007** [comment]
If you send me an e-mail I can give you a test account on one of our SMTP servers to try.

**Comment by adarshkhatri** [comment]
Thanks

I have resolved this issue. It was my xampp not allowing SMTP.
