### ISSUE TITLE
Route with name "login" not found

### ISSUE THREAD

**Issue by adarshkhatri** [coolcsn/CsnUser#35]
Hi

Not sure if it is csn-user error or csn-authorization error.

When I click on confirmation email link, I get this error:
I even tried to edit db directly to allow to set email confirmed to yes, state to "member = 2", with this I am able to login but same error when I try to edit the profile.

Fatal error: Uncaught exception 'Zend\Mvc\Router\Exception\RuntimeException' with message 'Route with name "login" not found' in /Applications/XAMPP/xamppfiles/htdocs/skeleton/vendor/zendframework/zend-mvc/src/Router/Http/TreeRouteStack.php:317 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/skeleton/vendor/coolcsn/csn-authorization/src/CsnAuthorization/Module.php(64): Zend\Mvc\Router\Http\TreeRouteStack->assemble(Array, Array) #1 [internal function]: CsnAuthorization\Module->onRoute(Object(Zend\Mvc\MvcEvent)) #2 /Applications/XAMPP/xamppfiles/htdocs/skeleton/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #3 /Applications/XAMPP/xamppfiles/htdocs/skeleton/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('route', Object(Zend\Mvc\MvcEvent), Object(Closure)) #4 /Applications/XAMPP/xamppfiles/htdocs/skeleton/vendor/zendframework/zend-mvc/src/Application.php(297): Zend\EventManager\EventMan in /Applications/XAMPP/xamppfiles/htdocs/skeleton/vendor/zendframework/zend-mvc/src/Router/Http/TreeRouteStack.php on line 317

Please suggest.

**Comment by adarshkhatri** [comment]
This is csn-authorization error.

**Comment by wingman007** [comment]
Thank you for opening this issue. We will try to find a solution.
