### ISSUE TITLE
Confirm email redirects to login page but user is still disabled

### ISSUE THREAD

**Issue by adarshkhatri** [coolcsn/CsnUser#37]
Hi

I am stuck here.
When signup it sends an email and while I click on email, it then redirects me to login page.

But now when I login, it says user is disabled.

When I check database, "email confirm" section is 0.

Please suggest.

**Comment by coolcsn** [comment]
Hello Adarsh,

I guess you have again problems with the Authorization.
If you get redirected that means maybe CsnAuthorization is not allowing you
to reach the resource for e-mail confirmation.
Make sure everyone can access the controller 'CsnUser\Controller\Registration'
and its action 'confirmEmail' => 'guest' This is how this is done in '
_acl.global.php'_

_..._
- 'allow' => array( 'CsnUser\Controller\Registration' => array( 'index' =>
  'guest', 'changePassword' => 'member', 'editProfile' => 'member',
  'changeEmail' => 'member', 'forgottenPassword' => 'guest', 'confirmEmail'
  => 'guest', 'registrationSuccess' => 'guest', ), ... Notice 'confirmEmail'
  => 'guest', B.T.W. We had to start with that. Make sure you have
  acl.global.php in your <project>/config/autoload folder :) It controls the
  Authorization module. I hope this helps! Stoyan :)*

**Comment by wingman007** [comment]
Why don't you try to disable the CsnAuthorization module and try again. Because I think it is Authorization problem.

**Comment by adarshkhatri** [comment]
Thank you for reply, it was authorization problem, that's why I closed the issue.

Thanks again.
