### ISSUE TITLE
Error message while login

### ISSUE THREAD

**Issue by adarshkhatri** [coolcsn/CsnUser#38]
I am receiving error message while login.

Notice: Undefined offset: 0 in /Applications/XAMPP/xamppfiles/htdocs/skeleton/vendor/coolcsn/csn-user/src/CsnUser/Controller/IndexController.php on line 89

This is displayed only sometime, I guess when my login credentials are wrong. But not sure when exactly.

**Comment by wingman007** [comment]
Try to fix it as other users did (https://github.com/coolcsn/CsnUser/issues/36)

222: $user = $user[0];

The lines give error if you user does not exist who is trying to reset password.

I have replaced it with

222: $user = isset($user[0])?$user[0]:null;

it is working fine now..

**Comment by adarshkhatri** [comment]
thank you

**Comment by qwesy** [comment]
Hi, I am receiving error message while login:
"A record with the supplied identity could not be found. "

I have registered users and confirmed with email using the registration form, but i still cant login.
please help me.
