### ISSUE TITLE
Add new field in signup

### ISSUE THREAD

**Issue by adarshkhatri** [coolcsn/CsnUser#39]
I am trying to add new input field in signup and edit user section.

However I am not sure where to add the form declaration for that field.

I have created a new column in user table, which is defined as FK.

Please help.

**Comment by wingman007** [comment]
If you are using Doctrine it is a good idea to declare a new field and metadata for it in the model "User" I guess in this case. 
Notice: We are using the "Code first" approach by using Doctrine
1. You don't create new fields in the table. You just add the new property in the class User (model). Yo also add all necessary metadata for this property in the very same file where User class lives. 
2. You run the doctrine-module tool to ask Doctrine to do its magic and add the field to your table by typing (on windows) vendor\bin\doctrine-module.bat list to see all commands. Chose the one for updating the schema. This will create a field for you.
3. Make sure in your view you have few lines or a line to display the form field.

**Comment by adarshkhatri** [comment]
I see,

BTW when I declare form in view (phtml) file:
$form->get('my_field')->setAttributes(array(
    'required' => 'true',
    'class' => 'form-control input-lg',
));

it throws an error.
I have added a new entity file too.

Not sure if I try with your code first approach and run doctorine will fix this.

I will give this try tonight.

Thanks again.

**Comment by adarshkhatri** [comment]
This solved my requirement.
