### ISSUE TITLE
Add new roles

### ISSUE THREAD

**Issue by boedociclon** [coolcsn/CsnUser#40]
Hi again, I tried add a role between guest and admin, let's say super-member, and I got an error using db configuration.
I figured out where the problem is and I need an advice about solutions I found.

I have following roles records:
id:1;name:guest;
id:2;name:member;
id:3;name:admin;
id:4;name:super-member;

I also have following roles_parents records:
role: member; parent: guest;
role: super-member; parent: member;
role: admin; parent: super-member;

Problem arises because findAll() method of role entity returns records ordered by id: so when AclDb class in CsnAuthorization module calls addRole() it passes first admin role whith its parents, i.e. member and super-member, but while member was already passed because of its lower id, super-member was not because it was added in second time and its id is grater, and this causes a fatal error.

I found two solutions:
1 - use naming convention for roles and then order roles by name asc:
new roles: 000guest , 100member , 200super-member , 300admin
and change AclDb constructor code like this:
old:
$roles = $entityManager->getRepository('CsnUser\Entity\Role')->findAll();
new:
$roles = $entityManager->getRepository('CsnUser\Entity\Role')->findBy(array(), array('name' => 'ASC'));

2 - add "weight" property to role entity and define a custom findAll() method inside entity repository (I foud this solution here: http://goo.gl/rQbWZS ):

roles records:
id:1;name:guest;weight:0;
id:2;name:member;weight:1;
id:3;name:admin;weight:3;
id:4;name:super-member;weight:2;

File RoleRepository.php

...
class RoleRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('weight' => 'ASC'));
    }
}

File Role.php

...
- @ORM\Entity(repositoryClass="CsnUser\Entity\Repository\RoleRepository")
- @ORM\Table(name="role")
  */
  class Role
  {
  ...
  - @var integer
    *
  - @ORM\Column(name="weight", type="integer", nullable=false)
    */
    protected $weight;
    ...
    }

I think second one is better because it is completely transparent to CsnAuthorization module. First one is a kind of hack.
Can you please check these solutions and give me your opinion?
Maybe your modules provides better solutions to add roles in second time, if not I hope this one is useful.
Thanks.
Best regards,
Davide.

**Comment by wingman007** [comment]
Thank you for sharing this with us. I like your second approach for solving the problem, by adding  "weight" property to role entity.
